// data_destinasi.dart

class DataDestinasi {
  static final List<Map<String, dynamic>> semuaDestinasi = [
    // --- DATA DARI gunung.dart ---
    {
      'nama': 'Gunung Rinjani',
      'wilayah': 'Bali dan Nusa Tenggara',
      'lokasi': 'Lombok, NTB',
      'ketinggian': '3.726 MDPL',
      'estimasi': '3 Hari 2 Malam',
      'jalur': 'Sembalun, Senaru, Torean',
      'kategori': 'Gunung',
      'image': 'assets/rinjani.png',
      'Tarif Hari Kerja (WNA)': '150.000',
      'Tarif Akhir Pekan (WNA)': '250.000',
      'Tarif Hari Kerja (WNI)': '5.000',
      'Tarif Akhir Pekan (WNI)': '7.500',
    },
    {
      'nama': 'Gunung Merbabu',
      'wilayah': 'Jawa',
      'lokasi': 'Boyolali, Jawa Tengah',
      'ketinggian': '3.142 MDPL',
      'estimasi': '8 - 10 Jam',
      'jalur': 'Selo, Suwanting, Wekas',
      'kategori': 'Gunung',
      'image': 'assets/merbabu.png',
      'Tarif Hari Kerja (WNA)': '200.000',
      'Tarif Akhir Pekan (WNA)': '300.000',
      'Tarif Hari Kerja (WNI)': '20.000',
      'Tarif Akhir Pekan (WNI)': '30.000',
    },
    {
      'nama': 'Gunung Arjuna',
      'wilayah': 'Jawa',
      'lokasi': 'Pasuruan, Jawa Timur',
      'ketinggian': '3.339 MDPL',
      'estimasi': '2 Hari 1 Malam',
      'jalur': 'Tretes, Purwosari, Lawang',
      'kategori': 'Gunung',
      'image': 'assets/arjuno.png',
      'Tarif Hari Kerja (WNA)': '200.000',
      'Tarif Akhir Pekan (WNA)': '200.000',
      'Tarif Hari Kerja (WNI)': '20.000',
      'Tarif Akhir Pekan (WNI)': '25.000',
    },
    {
      'nama': 'Gunung Kerinci',
      'wilayah': 'Sumatra',
      'lokasi': 'Kerinci, Jambi',
      'ketinggian': '3.805 MDPL',
      'estimasi': '2 Hari 1 Malam',
      'jalur': 'Kersik Tuo',
      'kategori': 'Gunung',
      'image': 'assets/kerinci.png',
      'Tarif Hari Kerja (WNA)': '310.000',
      'Tarif Akhir Pekan (WNA)': '460.000',
      'Tarif Hari Kerja (WNI)': '20.000',
      'Tarif Akhir Pekan (WNI)': '25.000',
    },
    {
      'nama': 'Gunung Lawu',
      'wilayah': 'Jawa',
      'lokasi': 'Karanganyar, Jawa Tengah',
      'ketinggian': '3.265 MDPL',
      'estimasi': '7 - 9 Jam',
      'jalur': 'Cetho, Cemoro Sewu, Cemoro Kandang',
      'kategori': 'Gunung',
      'image': 'assets/lawu.png',
      'Tarif Hari Kerja (WNA)': '25.000',
      'Tarif Akhir Pekan (WNA)': '35.000',
      'Tarif Hari Kerja (WNI)': '20.000',
      'Tarif Akhir Pekan (WNI)': '30.000',
    },

    // --- DATA DARI pantai.dart ---
    {
      'nama': 'Pantai Tanjung Tinggi',
      'wilayah': 'Sumatra',
      'lokasi': 'Belitung, Bangka Belitung',
      'kategori': 'Pantai',
      'tipe_pasir': 'Putih Halus', // Tambahan data tipe pasir
      'suhu': '29°C', // Tambahan data suhu
      'image': 'assets/tanjungT.png',
      'jalur':
          'Akses aspal mulus, dapat ditempuh 45 menit dari pusat Kota Tanjung Pandan.',
      'Tarif Hari Kerja (WNA)': '20.000',
      'Tarif Akhir Pekan (WNA)': '20.000',
      'Tarif Hari Kerja (WNI)': '5.000',
      'Tarif Akhir Pekan (WNI)': '5.000',
    },
    {
      'nama': 'Pantai Pink',
      'wilayah': 'Bali dan Nusa Tenggara',
      'lokasi': 'Lombok, NTB',
      'kategori': 'Pantai',
      'tipe_pasir': 'Pink Merah Muda',
      'suhu': '30°C',
      'image': 'assets/pink.png',
      'jalur':
          'Akses terbaik menggunakan kapal cepat dari Pelabuhan Tanjung Luar.',
      'Tarif Hari Kerja (WNA)': '50.000',
      'Tarif Akhir Pekan (WNA)': '50.000',
      'Tarif Hari Kerja (WNI)': '10.000',
      'Tarif Akhir Pekan (WNI)': '10.000',
    },
    {
      'nama': 'Pantai Tanjung Bira',
      'wilayah': 'Sulawesi',
      'lokasi': 'Bulukumba, Sulawesi Selatan',
      'kategori': 'Pantai',
      'tipe_pasir': 'Putih Kristal',
      'suhu': '28°C',
      'image': 'assets/tanjungB.png',
      'jalur':
          'Jalan raya trans Sulawesi dengan pemandangan pesisir yang indah.',
      'Tarif Hari Kerja (WNA)': '40.000',
      'Tarif Akhir Pekan (WNA)': '50.000',
      'Tarif Hari Kerja (WNI)': '15.000',
      'Tarif Akhir Pekan (WNI)': '20.000',
    },
    {
      'nama': 'Pantai Kuta',
      'wilayah': 'Bali dan Nusa Tenggara',
      'lokasi': 'Badung, Bali',
      'kategori': 'Pantai',
      'tipe_pasir': 'Putih Kecokelatan',
      'suhu': '31°C',
      'image': 'assets/kuta.png',
      'jalur':
          'Lokasi sangat strategis di pusat pariwisata, dekat dengan Bandara Ngurah Rai.',
      'Tarif Hari Kerja (WNA)': '0',
      'Tarif Akhir Pekan (WNA)': '0',
      'Tarif Hari Kerja (WNI)': '0',
      'Tarif Akhir Pekan (WNI)': '0',
    },

    // --- DATA DARI danau.dart ---
    {
      'nama': 'Danau Labuan Cermin',
      'wilayah': 'Kalimantan',
      'lokasi': 'Berau, Kalimantan Timur',
      'kategori': 'Danau',
      'kedalaman': '15 Meter',
      'status': 'Aman Berenang',
      'image': 'assets/LabuanC.png',
      'jalur': 'Akses menggunakan perahu sewa dari dermaga Desa Biduk-Biduk.',
      'Tarif Hari Kerja (WNA)': '50.000',
      'Tarif Akhir Pekan (WNA)': '50.000',
      'Tarif Hari Kerja (WNI)': '15.000',
      'Tarif Akhir Pekan (WNI)': '15.000',
    },
    {
      'nama': 'Danau Sentani',
      'wilayah': 'Maluku dan Papua',
      'lokasi': 'Jayapura, Papua',
      'kategori': 'Danau',
      'kedalaman': '75 Meter',
      'status': 'Wisata Perahu',
      'image': 'assets/Sentani.png',
      'jalur':
          'Dapat diakses langsung melalui jalan raya utama Jayapura-Sentani.',
      'Tarif Hari Kerja (WNA)': '10.000',
      'Tarif Akhir Pekan (WNA)': '10.000',
      'Tarif Hari Kerja (WNI)': '10.000',
      'Tarif Akhir Pekan (WNI)': '10.000',
    },
    {
      'nama': 'Danau Kelimutu',
      'wilayah': 'Bali dan Nusa Tenggara',
      'lokasi': 'Ende, NTT',
      'kategori': 'Danau',
      'kedalaman': '127 Meter',
      'status': 'Hanya Observasi',
      'image': 'assets/Kelimutu.png',
      'jalur': 'Jalur aspal mendaki dari Desa Moni hingga area parkir puncak.',
      'Tarif Hari Kerja (WNA)': '150.000',
      'Tarif Akhir Pekan (WNA)': '150.000',
      'Tarif Hari Kerja (WNI)': '20.000',
      'Tarif Akhir Pekan (WNI)': '20.000',
    },
    {
      'nama': 'Danau Toba',
      'wilayah': 'Sumatra',
      'lokasi': 'Samosir, Sumatra Utara',
      'kategori': 'Danau',
      'kedalaman': '505 Meter',
      'status': 'Aman Berenang',
      'image': 'assets/Toba.png',
      'jalur': 'Akses kapal feri dari Pelabuhan Ajibata menuju Tomok/Tuktuk.',
      'Tarif Hari Kerja (WNA)': '30.000',
      'Tarif Akhir Pekan (WNA)': '40.000',
      'Tarif Hari Kerja (WNI)': '15.000',
      'Tarif Akhir Pekan (WNI)': '20.000',
    },
    {
      'nama': 'Danau Kumbolo',
      'wilayah': 'Jawa',
      'lokasi': 'Lumajang, Jawa Timur',
      'kategori': 'Danau',
      'kedalaman': '28 Meter',
      'status': 'Dilarang Berenang',
      'image': 'assets/Kumbolo.png',
      'jalur':
          'Trekking melalui jalur pendakian Gunung Semeru (Pos Ranu Pani).',
      'Tarif Hari Kerja (WNA)': '210.000',
      'Tarif Akhir Pekan (WNA)': '310.000',
      'Tarif Hari Kerja (WNI)': '19.000',
      'Tarif Akhir Pekan (WNI)': '24.000',
    },

    // --- DATA DARI air_terjun.dart ---
    {
      'nama': 'Madakaripura',
      'wilayah': 'Jawa',
      'lokasi': 'Probolinggo, Jawa Timur',
      'jarak_trek': '1.5 KM',
      'durasi': '30 - 45 Menit',
      'jalur': 'Pintu Utama Madakaripura',
      'kategori': 'Air Terjun',
      'image': 'assets/madakaripura.png',
      'Tarif Hari Kerja (WNA)': '50.000',
      'Tarif Akhir Pekan (WNA)': '60.000',
      'Tarif Hari Kerja (WNI)': '25.000',
      'Tarif Akhir Pekan (WNI)': '33.000',
    },
    {
      'nama': 'Coban Talun',
      'wilayah': 'Jawa',
      'lokasi': 'Batu, Jawa Timur',
      'jarak_trek': '800 Meter',
      'durasi': '15 - 20 Menit',
      'jalur': 'Jalur Hutan Pinus',
      'kategori': 'Air Terjun',
      'image': 'assets/cobanT.png',
      'Tarif Hari Kerja (WNA)': '12.000',
      'Tarif Akhir Pekan (WNA)': '12.000',
      'Tarif Hari Kerja (WNI)': '12.000',
      'Tarif Akhir Pekan (WNI)': '12.000',
    },
    {
      'nama': 'Tegunungan',
      'wilayah': 'Bali dan Nusa Tenggara',
      'lokasi': 'Gianyar, Bali',
      'jarak_trek': '500 Meter',
      'durasi': '10 Menit',
      'jalur': 'Anak Tangga Beton',
      'kategori': 'Air Terjun',
      'image': 'assets/tegunungan.png',
      'Tarif Hari Kerja (WNA)': '20.000',
      'Tarif Akhir Pekan (WNA)': '20.000',
      'Tarif Hari Kerja (WNI)': '20.000',
      'Tarif Akhir Pekan (WNI)': '20.000',
    },
    {
      'nama': 'Sekumpul',
      'wilayah': 'Bali dan Nusa Tenggara',
      'lokasi': 'Buleleng, Bali',
      'jarak_trek': '2 KM',
      'durasi': '1 Jam',
      'jalur': 'Jalur Trekking Lemukih',
      'kategori': 'Air Terjun',
      'image': 'assets/sekumpul.png',
      'Tarif Hari Kerja (WNA)': '20.000',
      'Tarif Akhir Pekan (WNA)': '20.000',
      'Tarif Hari Kerja (WNI)': '10.000',
      'Tarif Akhir Pekan (WNI)': '10.000',
    },

    // --- DATA TAMBAHAN UNTUK REKOMENDASI (Sesuai main.dart Anda) ---
    {
      'nama': 'Gunung Rinjani',
      'wilayah': 'Bali dan Nusa Tenggara',
      'lokasi': 'Lombok, NTB',
      'ketinggian': '3.726 MDPL',
      'estimasi': '3 Hari 2 Malam',
      'jalur': 'Sembalun, Senaru, Torean',
      'kategori': 'Gunung',
      'image': 'assets/rinjani.png',
      'Tarif Hari Kerja (WNA)': '150.000',
      'Tarif Akhir Pekan (WNA)': '250.000',
      'Tarif Hari Kerja (WNI)': '5.000',
      'Tarif Akhir Pekan (WNI)': '7.500',
    },
    {
      'nama': 'Pantai Tanjung Tinggi',
      'wilayah': 'Sumatra',
      'lokasi': 'Belitung, Bangka Belitung',
      'ketinggian': '-',
      'estimasi': 'Fleksibel',
      'jalur': 'Akses Darat',
      'kategori': 'Pantai',
      'image': 'assets/tanjungT.png',
      'Tarif Hari Kerja (WNA)': '10.000',
      'Tarif Akhir Pekan (WNA)': '15.000',
      'Tarif Hari Kerja (WNI)': '5.000',
      'Tarif Akhir Pekan (WNI)': '5.000',
    },
    {
      'nama': 'Danau Labuan Cermin',
      'wilayah': 'Kalimantan',
      'lokasi': 'Berau, Kalimantan Timur',
      'ketinggian': '-',
      'estimasi': '2-4 Jam',
      'jalur': 'Akses Kapal',
      'kategori': 'Danau',
      'image': 'assets/LabuanC.png',
      'Tarif Hari Kerja (WNA)': '20.000',
      'Tarif Akhir Pekan (WNA)': '20.000',
      'Tarif Hari Kerja (WNI)': '10.000',
      'Tarif Akhir Pekan (WNI)': '10.000',
    },
  ];
}
